Allow source ID ot be saved as FHIR logical ID, map between source id and interaction id
jembi/mpi-mediator pull request #39
Opened 2024-03-14 07:42 UTC by rcrichton

This pull request adds functionality to save by source ID and swaps the source ID for the interaction ID in the FHIR Patient endpoint.

To use this OpenHIM channels must also be edited. The JeMPI channel patttern must be changed to `/fhir/Patient\??[^/]*` to allow the MPI mediator to handle `/Patient/<surceId>` queries.

2024-03-17 13:42 UTC, BMartinos reviewed
Overall the changes looks good to me :+1: 
I have been able to successfully look up the patient on /fhir/Patient/UUID (supplied in the creation). 
The supplied UUID is able to be used on the various other FHIR requests.

Still just doing a couple of other test cases which ive run into some issues (mostly edge cases), but all happy paths requests are looking good

2024-05-02 09:49 UTC, MatthewErispe commented on src/routes/index.ts
> +  let upsteamId = requestedId;
@bradsawadye typo here, should be upstreamId?

2024-05-02 10:27 UTC, MatthewErispe requested changes
@bradsawadye ltgm apart from one typo

2024-05-02 11:02 UTC, MatthewErispe approved these changes

2024-05-02 11:39 UTC, merged

2024-05-03 06:59 UTC, brett-onions reviewed
LGTM